export const globalStyles = {
    centeredPageContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', width: '100vw', fontFamily: "'Poppins', sans-serif", background: 'linear-gradient(135deg, #121212 0%, #1E1E1E 50%, #2A2A2A 100%)', },
    card: { backgroundColor: 'rgba(30, 30, 30, 0.7)', backdropFilter: 'blur(10px)', padding: '40px', borderRadius: '12px', boxShadow: '0 10px 30px rgba(0,0,0,0.5)', width: '420px', textAlign: 'center', border: '1px solid rgba(255, 255, 255, 0.1)', },
    input: { width: '100%', padding: '14px 20px', margin: '10px 0', backgroundColor: 'rgba(0, 0, 0, 0.3)', color: 'var(--text-primary)', border: '1px solid #444', borderRadius: '8px', fontSize: '16px', transition: 'border-color 0.2s, box-shadow 0.2s' },
    primaryButton: { width: '100%', padding: '14px', marginTop: '15px', background: 'linear-gradient(90deg, #007BFF, #00BFFF)', color: 'white', cursor: 'pointer', borderRadius: '8px', border: 'none', fontWeight: '600', fontSize: '16px', transition: 'transform 0.2s, box-shadow 0.2s', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px' },
    secondaryButton: { width: '100%', padding: '14px', marginTop: '10px', backgroundColor: 'var(--secondary-gray)', color: 'white', cursor: 'pointer', borderRadius: '8px', border: 'none', fontWeight: '600', fontSize: '16px', transition: 'background-color 0.2s, transform 0.1s' },
    heading: { color: 'var(--text-primary)', marginBottom: '25px', fontWeight: '600' },
};
export const dashboardStyles = {
    container: { display: 'flex', height: '100vh', fontFamily: "'Poppins', sans-serif", position: 'relative', },
    controlPanel: { width: '400px', minWidth: '400px', height: '100vh', padding: '25px', backgroundColor: 'var(--dark-surface)', color: 'var(--text-primary)', borderRight: '1px solid #333', display: 'flex', flexDirection: 'column', gap: '20px', overflowY: 'auto', },
    header: { color: 'var(--accent-cyan)', paddingBottom: '10px', fontSize: '24px', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '12px', margin: 0, flexShrink: 0 },
    subHeader: { color: 'var(--text-secondary)', textTransform: 'uppercase', fontSize: '12px', fontWeight: '600', letterSpacing: '1px', marginBottom: '15px', display: 'flex', alignItems: 'center', gap: '8px' },
    statCard: { backgroundColor: 'var(--dark-card)', padding: '15px', borderRadius: '10px', border: '1px solid #333', flexShrink: 0 },
    driverMetricsContainer: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' },
    driverMetricBox: { backgroundColor: 'var(--dark-card)', padding: '15px', borderRadius: '10px', textAlign: 'center' },
    driverMetricLabel: { color: 'var(--text-secondary)', fontSize: '12px', textTransform: 'uppercase', margin: '0 0 5px 0' },
    driverMetricValue: { color: 'var(--accent-yellow)', fontSize: '24px', fontWeight: '600', margin: 0 },
    driverInstructionCard: { backgroundColor: 'var(--primary-blue)', borderRadius: '12px', padding: '25px', textAlign: 'center', flexGrow: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' },
    eventLogContainer: { backgroundColor: 'var(--dark-card)', padding: '15px', borderRadius: '10px', border: '1px solid #333', height: '250px', display: 'flex', flexDirection: 'column', flexShrink: 0 },
    eventLogContent: { flexGrow: 1, overflowY: 'auto', fontFamily: 'monospace', fontSize: '14px', },
    signalEntry: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px', padding: '12px', backgroundColor: 'var(--dark-card)', borderRadius: '8px', border: '1px solid #333', },
    overrideButton: { backgroundColor: 'transparent', color: 'var(--accent-yellow)', border: '1px solid var(--accent-yellow)', borderRadius: '6px', padding: '5px 10px', cursor: 'pointer', transition: 'background-color 0.2s, color 0.2s', fontSize: '12px', },
    trafficIndicator: { padding: '3px 8px', borderRadius: '12px', fontSize: '12px', fontWeight: 'bold', color: 'white', },
    mapContainer: { flexGrow: 1, backgroundColor: 'var(--dark-bg)' },
};